### ISSUE TITLE
recv_world_video_frames.py

### ISSUE THREAD

**Issue by seMartin1337** [pupil-labs/pupil-helpers#11]
Hello,
if i use recv_world_video_frames.py as it is i get
```
topic,msg = sub.recv()
ValueError: too many values to unpack (expected 2)
```
if i split the line to look like
```
topic = sub.recv_string()
msg = sub.recv()
```
creating the image ends with
```
img = np.frombuffer(msg['__raw_data__'][0]).reshape(720,1280,3)
TypeError: byte indices must be integers or slices, not str
```

i tried 
```
img = np.frombuffer(msgpack.loads(msg)['__raw_data__'][0]).reshape(720,1280,3)
```
which tells me that there's a key error with '__raw_data__'
am i missing something here?
Best regards
M

**Comment by mkassner** [comment]
@papr  please have a look at this. I m sure I just messed up something while blind coding.

**Comment by seMartin1337** [comment]
wow, thanks for the fast and great work!
br M
