### ISSUE TITLE
free pascal api

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil-helpers#19]
Hi, I have organized a repository with stuff that may be useful for talking to pupil from free pascal. It includes a class for applications (Pupil Client) and a no gui example (Pupil Tasks):  
https://github.com/cpicanco/pupil-fpc-examples

See `/examples/pupil_client.pas` and `/examples/pupil_task.pas`.

If you do not want all examples (and all dependencies) you can use https://github.com/cpicanco/pupil-fpc instead.

**Comment by willpatera** [comment]
Hi @cpicanco it would be really nice to have more documentation in the READMEs of these repos.

**Comment by cpicanco** [comment]
Sure, I will be working on the readmes today:

- actual functionality
- basic use cases
- steps to execute pupil and the examples.

**Comment by cpicanco** [comment]
Getting there! Please, take a look @willpatera 
https://github.com/cpicanco/pupil-fpc/blob/master/README.md

**Comment by cpicanco** [comment]
@willpatera, ok, reviewed and updated!

https://github.com/cpicanco/pupil-fpc/blob/master/README.md

https://github.com/cpicanco/pupil-fpc-examples/blob/master/README.md

**Comment by willpatera** [comment]
@cpicanco Your bindings are now listed in the readme of this project with https://github.com/pupil-labs/pupil-helpers/commit/17d6ea809f3e5667f79c6919ee82b07fbb0d3399 - I will now close this issue.
