### ISSUE TITLE
pupil_remote_control.m: Variable "req_socket" is not defined

### ISSUE THREAD

**Issue by thebau** [pupil-labs/pupil-helpers#29]
Hello!

I'm getting following error, running pupil_remote_control.m:

```
Undefined function or variable 'req_socket'.

Error in pupil_remote_control (line 21)
zmq.core.setsockopt(req_socket, 'ZMQ_RCVTIMEO', 1000);
```

Looking at the Matlab code, i see that the variable 'req_socket' is not defined before. Is this an issue and if, is there an workaround?

best regards!

**Comment by papr** [comment]
Hey @thebau 
Thank you for your report!

Yes, this is a bug. Please try to rename it to `socket`. I would be happy if you could create a push request with the fix if it works.

**Comment by thebau** [comment]
Hello @papr 

it works by renaming it to socket, thank you! I have created a pull request. As i'm new to github i hope i've done it correctly.

Best regards!
