### ISSUE TITLE
[Q] Calling Pupil_Sync_Node.notify_all on main thread

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-helpers#3]
This more a question than an issue.

I am using the `pupil_sync_complete.py` example for one of my projects. But I would like to process the incoming notifications on the main thread since I have some UI stuff to do. In [pupil_sync_complete.py, l.328](https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_sync/pupil_sync_complete.py#L328) `notify_all()` is called in the background thread. This is undesirable for me.

Is there an easy way to call this function on the main thread?
If not: My idea was to send it back using the `pipe` and manually checking `self.thread_pipe` for `POLLIN` events in the main thread. This way I have to manipulate the original code. Is there a way to implement this by subclassing `Pupil_Sync_Node` and not rewriting the complete `_thread_loop()` method?

**Comment by mkassner** [comment]
What about overwriting https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_sync/pupil_sync_complete.py#L73

Use a threading.Queue.Queue and put things into the queue in this callback fn.

In your main thread you can empty the queue.

**Comment by papr** [comment]
Thank you very much. This looks like a clean idea.
