### ISSUE TITLE
Matlab crashes after running "pupil_remote_control.m"

### ISSUE THREAD

**Issue by limt1** [pupil-labs/pupil-helpers#36]
Hi there, 
I followed the steps in "readme" and everything seemed to be ok but when I tried to run the file, matlab just crashed... 

System info:
Windows 10 64
matlab 2019a 
ZeroMQ: 4.3.2 
PupilCapture: 1.13-29

Thank you

**Comment by papr** [comment]
Apologies for not having responded at the time. Unfortunately, we cannot give advise/support regarding the installation of the Matlab dependencies. Feel free to reach out to the community on our [Discord server](https://pupil-labs.com/chat) if the issue persists.
