### ISSUE TITLE
Undefined function/ variable 'socket'

### ISSUE THREAD

**Issue by graceshaib** [pupil-labs/pupil-helpers#37]
Hello,

Im trying to run recv_message.m on matlab. I opened pupil capture on the side and downloaded the two folder packages "msgpac" and "zmq" and placed them on my desktop. However, whenever I run the code, I receive an error that that "undefined function or variable 'socket'" Can anyone help me out with this?

**Comment by papr** [comment]
@graceshaib If you were able to solve it, please let us know if it was a setup issue or if you had to modify the script to get it working.

**Comment by graceshaib** [comment]
It was a set up issue, the script is fine. However, now I'm having problems with the mex configuration. Your help in this would be very much appreciated.

**Comment by graceshaib** [comment]
Should I replace the socket with another input?

**Comment by papr** [comment]
Apologies for not having responded to your issue at the time. We cannot give any advise/support regarding the mex configuration.
