### ISSUE TITLE
Application of the mouse_control.py for the Pupil Invisible

### ISSUE THREAD

**Issue by Mystike30** [pupil-labs/pupil-helpers#49]
Hello,

I would like to apply the code "mouse_control.py" of the Pupil Capture for the Pupil Invisible. What should I change in the code to use that for the Pupil Invisible ?

Thanks.

**Comment by papr** [comment]
Hi, unfortunately, this example is not compatible with Pupil Invisible because it requires realtime surface tracking which is only available within the Pupil Core applications.
