### ISSUE TITLE
Update `mouse_control.py` to work with current version of Pupil Capture

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-helpers#7]
The message pattern has changed. We should now subscribe to `surface` and use the `norm_pos` from `['gaze_on_surface']`

**Comment by cpicanco** [comment]
Why not a capture/server plugin for this?

**Comment by cpicanco** [comment]
First of all, mouse control is something expected by any screen based eye tracking system. I feel that it is something that PUPIL should have too, even being above all a pervasive system.

Mouse control depends on a screen surface. Right now, a "screen surface" can be returned through the marker detector or using the plugin I have written inherited from the marker detector.

The plugin could have;

- text input to the desired "screen surface name" to be found
-  "mouse detection".

Mouse control also depends on good homography, afaik. Homography is good enough right now and can be optimized with time; the plugin would help. Of course, good calibration is also needed.

Would be great to have the possibility to control the mouse of different computers by looking at them, but I am just dreaming. :smile:

**Comment by erykczekaj** [comment]
Hi, when trying to run the code, there's a KeyError in this statement: `if gaze_position["name"] == surface_name:`

**Comment by willpatera** [comment]
@erykczekaj did you name your surface in Pupil Capture? The `mouse_control.py` script expects the surface to be named `screen`. You can name the surface whatever you want it to be named, but just make sure that the name in Pupil Capture corresponds exactly to the name in https://github.com/pupil-labs/pupil-helpers/blob/master/python/mouse_control.py#L8

Also AFAIK, @papr updated this script a couple weeks ago and it should now be working with the latest release of Pupil Capture. I will close this issue due to recent commits that should have fixed any issues with version compatibility.

**Comment by papr** [comment]
@erykczekaj one small addition: For the current version of the script, you will need to run the newest version of Pupil Capture: https://github.com/pupil-labs/pupil/releases/tag/v1.13
